//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnrealShopCompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderSet()
        {
            this.Return = new HashSet<Return>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdClients { get; set; }
        public Nullable<int> IdItems { get; set; }
        public int IdUsers { get; set; }
        public Nullable<int> Number { get; set; }
        public double Discount { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Items Items { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Return> Return { get; set; }
    }
}
