//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnrealShopCompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class Return
    {
        public int Id { get; set; }
        public Nullable<int> IdOrder { get; set; }
        public int NumberReturn { get; set; }
        public int StaffName { get; set; }
        public string Status { get; set; }
    
        public virtual OrderSet OrderSet { get; set; }
    }
}
